USE DATABASE PLANNING_DB; USE WAREHOUSE COMPUTE_WH; USE SCHEMA PLANNING;
DELETE FROM PLANNING.BUDGETLINEITEM;
DELETE FROM PLANNING.CONSOLIDATIONJOURNALLINE;
DELETE FROM PLANNING.CONSOLIDATIONJOURNAL;
DELETE FROM PLANNING.BUDGETHEADER;
DELETE FROM PLANNING.ALLOCATIONRULE;
DELETE FROM PLANNING.GLACCOUNT;
DELETE FROM PLANNING.COSTCENTER;
DELETE FROM PLANNING.FISCALPERIOD;
