USE DATABASE PLANNING_DB;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA PLANNING;

CREATE OR REPLACE FUNCTION PLANNING.FN_GETHIERARCHYPATH (
    P_COSTCENTERID  INTEGER,
    P_DELIMITER     VARCHAR DEFAULT ' > '
)
RETURNS VARCHAR
AS
$$
    WITH RECURSIVE HIER AS (
        SELECT
            CC.COSTCENTERID      AS NODEID,
            CC.PARENTCOSTCENTERID,
            CC.COSTCENTERNAME    AS NODENAME,
            0                    AS DEPTH
        FROM PLANNING.COSTCENTER CC
        WHERE CC.COSTCENTERID = P_COSTCENTERID

        UNION ALL

        SELECT
            P.COSTCENTERID,
            P.PARENTCOSTCENTERID,
            P.COSTCENTERNAME,
            H.DEPTH + 1
        FROM PLANNING.COSTCENTER P
        INNER JOIN HIER H ON P.COSTCENTERID = H.PARENTCOSTCENTERID
        WHERE H.DEPTH < 20
    )
    SELECT LISTAGG(NODENAME, P_DELIMITER) WITHIN GROUP (ORDER BY DEPTH DESC)
    FROM HIER
$$;

CREATE OR REPLACE FUNCTION PLANNING.FN_GETALLOCATIONFACTOR (
    P_SOURCECOSTCENTERID  INTEGER,
    P_TARGETCOSTCENTERID  INTEGER,
    P_ALLOCATIONBASIS     VARCHAR,
    P_FISCALPERIODID      INTEGER,
    P_BUDGETHEADERID      INTEGER
)
RETURNS NUMBER(18,10)
AS
$$
    SELECT
        CASE P_ALLOCATIONBASIS

            WHEN 'HEADCOUNT' THEN
                NVL(
                    (SELECT CC.ALLOCATIONWEIGHT
                     FROM PLANNING.COSTCENTER CC
                     WHERE CC.COSTCENTERID = P_TARGETCOSTCENTERID
                       AND CC.ISACTIVE = TRUE)
                    /
                    NULLIF(
                        (SELECT SUM(CC2.ALLOCATIONWEIGHT)
                         FROM PLANNING.COSTCENTER CC2
                         WHERE CC2.PARENTCOSTCENTERID = P_SOURCECOSTCENTERID
                           AND CC2.ISACTIVE = TRUE),
                        0),
                    0)

            WHEN 'REVENUE' THEN
                NVL(
                    (SELECT SUM(BLI.FINALAMOUNT)
                     FROM PLANNING.BUDGETLINEITEM BLI
                     INNER JOIN PLANNING.GLACCOUNT GLA ON BLI.GLACCOOUNTID = GLA.GLACCOOUNTID
                     WHERE BLI.COSTCENTERID = P_TARGETCOSTCENTERID
                       AND GLA.ACCOUNTTYPE = 'R'
                       AND BLI.FISCALPERIODID = P_FISCALPERIODID
                       AND (P_BUDGETHEADERID IS NULL OR BLI.BUDGETHEADERID = P_BUDGETHEADERID))
                    /
                    NULLIF(
                        (SELECT SUM(BLI2.FINALAMOUNT)
                         FROM PLANNING.BUDGETLINEITEM BLI2
                         INNER JOIN PLANNING.GLACCOUNT GLA2 ON BLI2.GLACCOOUNTID = GLA2.GLACCOOUNTID
                         INNER JOIN PLANNING.COSTCENTER CC3 ON BLI2.COSTCENTERID = CC3.COSTCENTERID
                         WHERE (CC3.PARENTCOSTCENTERID = P_SOURCECOSTCENTERID
                                OR CC3.COSTCENTERID = P_SOURCECOSTCENTERID)
                           AND GLA2.ACCOUNTTYPE = 'R'
                           AND BLI2.FISCALPERIODID = P_FISCALPERIODID
                           AND (P_BUDGETHEADERID IS NULL OR BLI2.BUDGETHEADERID = P_BUDGETHEADERID)),
                        0),
                    0)

            WHEN 'EXPENSE' THEN
                NVL(
                    (SELECT SUM(BLI.FINALAMOUNT)
                     FROM PLANNING.BUDGETLINEITEM BLI
                     INNER JOIN PLANNING.GLACCOUNT GLA ON BLI.GLACCOOUNTID = GLA.GLACCOOUNTID
                     WHERE BLI.COSTCENTERID = P_TARGETCOSTCENTERID
                       AND GLA.ACCOUNTTYPE = 'X'
                       AND BLI.FISCALPERIODID = P_FISCALPERIODID
                       AND (P_BUDGETHEADERID IS NULL OR BLI.BUDGETHEADERID = P_BUDGETHEADERID))
                    /
                    NULLIF(
                        (SELECT SUM(BLI2.FINALAMOUNT)
                         FROM PLANNING.BUDGETLINEITEM BLI2
                         INNER JOIN PLANNING.GLACCOUNT GLA2 ON BLI2.GLACCOOUNTID = GLA2.GLACCOOUNTID
                         INNER JOIN PLANNING.COSTCENTER CC3 ON BLI2.COSTCENTERID = CC3.COSTCENTERID
                         WHERE (CC3.PARENTCOSTCENTERID = P_SOURCECOSTCENTERID
                                OR CC3.COSTCENTERID = P_SOURCECOSTCENTERID)
                           AND GLA2.ACCOUNTTYPE = 'X'
                           AND BLI2.FISCALPERIODID = P_FISCALPERIODID
                           AND (P_BUDGETHEADERID IS NULL OR BLI2.BUDGETHEADERID = P_BUDGETHEADERID)),
                        0),
                    0)

            WHEN 'EQUAL' THEN
                NVL(
                    1.0 / NULLIF(
                        (SELECT COUNT(*)
                         FROM PLANNING.COSTCENTER CC4
                         WHERE CC4.PARENTCOSTCENTERID = P_SOURCECOSTCENTERID
                           AND CC4.ISACTIVE = TRUE),
                        0),
                    0)

            ELSE 0

        END
$$;

CREATE OR REPLACE FUNCTION PLANNING.TVF_GETBUDGETVARIANCE (
    P_BASEBUDGETHEADERID        INTEGER,
    P_COMPARISONBUDGETHEADERID  INTEGER,
    P_FISCALYEAR                SMALLINT  DEFAULT NULL,
    P_COSTCENTERID              INTEGER   DEFAULT NULL,
    P_ACCOUNTTYPE               CHAR(1)   DEFAULT NULL,
    P_VARIANCETHRESHOLDPCT      NUMBER(5,2) DEFAULT NULL
)
RETURNS TABLE (
    GLACCOOUNTID        INTEGER,
    ACCOUNTNUMBER       VARCHAR(20),
    ACCOUNTNAME         VARCHAR(150),
    ACCOUNTTYPE         CHAR(1),
    COSTCENTERID        INTEGER,
    COSTCENTERCODE      VARCHAR(20),
    COSTCENTERNAME      VARCHAR(100),
    FISCALPERIODID      INTEGER,
    FISCALYEAR          SMALLINT,
    FISCALMONTH         TINYINT,
    PERIODNAME          VARCHAR(50),
    BUDGETAMOUNT        NUMBER(19,4),
    COMPARISONAMOUNT    NUMBER(19,4),
    VARIANCEAMOUNT      NUMBER(19,4),
    VARIANCEPERCENTAGE  NUMBER(10,4),
    VARIANCESTATUS      VARCHAR(12),
    EXCEEDSTHRESHOLD    BOOLEAN
)
AS
$$
    WITH BASEBUDGET AS (
        SELECT
            BLI.GLACCOOUNTID,
            BLI.COSTCENTERID,
            BLI.FISCALPERIODID,
            SUM(BLI.FINALAMOUNT) AS BUDGETAMOUNT
        FROM PLANNING.BUDGETLINEITEM BLI
        WHERE BLI.BUDGETHEADERID = P_BASEBUDGETHEADERID
        GROUP BY BLI.GLACCOOUNTID, BLI.COSTCENTERID, BLI.FISCALPERIODID
    ),
    COMPARISONBUDGET AS (
        SELECT
            BLI.GLACCOOUNTID,
            BLI.COSTCENTERID,
            BLI.FISCALPERIODID,
            SUM(BLI.FINALAMOUNT) AS COMPARISONAMOUNT
        FROM PLANNING.BUDGETLINEITEM BLI
        WHERE BLI.BUDGETHEADERID = P_COMPARISONBUDGETHEADERID
        GROUP BY BLI.GLACCOOUNTID, BLI.COSTCENTERID, BLI.FISCALPERIODID
    ),
    COMBINED AS (
        SELECT
            COALESCE(B.GLACCOOUNTID, C.GLACCOOUNTID)     AS GLACCOOUNTID,
            COALESCE(B.COSTCENTERID, C.COSTCENTERID)     AS COSTCENTERID,
            COALESCE(B.FISCALPERIODID, C.FISCALPERIODID) AS FISCALPERIODID,
            NVL(B.BUDGETAMOUNT, 0)                       AS BUDGETAMOUNT,
            NVL(C.COMPARISONAMOUNT, 0)                   AS COMPARISONAMOUNT,
            NVL(C.COMPARISONAMOUNT, 0) - NVL(B.BUDGETAMOUNT, 0) AS VARIANCEAMOUNT,
            CASE
                WHEN NVL(B.BUDGETAMOUNT, 0) = 0 THEN NULL
                ELSE (NVL(C.COMPARISONAMOUNT, 0) - NVL(B.BUDGETAMOUNT, 0)) / B.BUDGETAMOUNT * 100
            END AS VARIANCEPERCENTAGE
        FROM BASEBUDGET B
        FULL OUTER JOIN COMPARISONBUDGET C
            ON B.GLACCOOUNTID   = C.GLACCOOUNTID
           AND B.COSTCENTERID   = C.COSTCENTERID
           AND B.FISCALPERIODID = C.FISCALPERIODID
    )
    SELECT
        COMB.GLACCOOUNTID,
        GLA.ACCOUNTNUMBER,
        GLA.ACCOUNTNAME,
        GLA.ACCOUNTTYPE,
        COMB.COSTCENTERID,
        CC.COSTCENTERCODE,
        CC.COSTCENTERNAME,
        COMB.FISCALPERIODID,
        FP.FISCALYEAR,
        FP.FISCALMONTH,
        FP.PERIODNAME,
        COMB.BUDGETAMOUNT,
        COMB.COMPARISONAMOUNT,
        COMB.VARIANCEAMOUNT,
        COMB.VARIANCEPERCENTAGE,
        CASE
            WHEN COMB.VARIANCEAMOUNT > 0 THEN 'FAVORABLE'
            WHEN COMB.VARIANCEAMOUNT < 0 THEN 'UNFAVORABLE'
            ELSE 'ON_TARGET'
        END AS VARIANCESTATUS,
        CASE
            WHEN ABS(COMB.VARIANCEPERCENTAGE) > NVL(P_VARIANCETHRESHOLDPCT, 100) THEN TRUE
            ELSE FALSE
        END AS EXCEEDSTHRESHOLD
    FROM COMBINED COMB
    INNER JOIN PLANNING.GLACCOUNT    GLA ON COMB.GLACCOOUNTID  = GLA.GLACCOOUNTID
    INNER JOIN PLANNING.COSTCENTER   CC  ON COMB.COSTCENTERID  = CC.COSTCENTERID
    INNER JOIN PLANNING.FISCALPERIOD FP  ON COMB.FISCALPERIODID = FP.FISCALPERIODID
    WHERE (P_FISCALYEAR IS NULL          OR FP.FISCALYEAR     = P_FISCALYEAR)
      AND (P_COSTCENTERID IS NULL        OR COMB.COSTCENTERID = P_COSTCENTERID)
      AND (P_ACCOUNTTYPE IS NULL         OR GLA.ACCOUNTTYPE   = P_ACCOUNTTYPE)
$$;

CREATE OR REPLACE FUNCTION PLANNING.TVF_EXPLODECOSTCENTERHIERARCHY (
    P_ROOTCOSTCENTERID  INTEGER   DEFAULT NULL,
    P_MAXDEPTH          INTEGER   DEFAULT 10,
    P_INCLUDEINACTIVE   BOOLEAN   DEFAULT FALSE,
    P_ASOFDATE          DATE      DEFAULT NULL
)
RETURNS TABLE (
    COSTCENTERID        INTEGER,
    COSTCENTERCODE      VARCHAR(20),
    COSTCENTERNAME      VARCHAR(100),
    PARENTCOSTCENTERID  INTEGER,
    HIERARCHYLEVEL      INTEGER,
    HIERARCHYPATH       VARCHAR(500),
    SORTPATH            VARCHAR(500),
    ISLEAF              BOOLEAN,
    CHILDCOUNT          INTEGER,
    CUMULATIVEWEIGHT    NUMBER(18,10)
)
AS
$$
    WITH RECURSIVE HIER AS (
        SELECT
            CC.COSTCENTERID,
            CC.COSTCENTERCODE,
            CC.COSTCENTERNAME,
            CC.PARENTCOSTCENTERID,
            0                                        AS HIERARCHYLEVEL,
            CC.COSTCENTERNAME::VARCHAR(500)          AS HIERARCHYPATH,
            LPAD(CC.COSTCENTERID::VARCHAR, 10, '0')  AS SORTPATH,
            CC.ALLOCATIONWEIGHT                      AS CUMULATIVEWEIGHT
        FROM PLANNING.COSTCENTER CC
        WHERE (
              (P_ROOTCOSTCENTERID IS NULL AND CC.PARENTCOSTCENTERID IS NULL)
           OR (CC.COSTCENTERID = P_ROOTCOSTCENTERID)
          )
          AND (P_INCLUDEINACTIVE = TRUE OR CC.ISACTIVE = TRUE)
          AND CC.EFFECTIVEFROMDATE <= NVL(P_ASOFDATE, CURRENT_DATE())
          AND (CC.EFFECTIVETODATE IS NULL OR CC.EFFECTIVETODATE >= NVL(P_ASOFDATE, CURRENT_DATE()))

        UNION ALL

        SELECT
            CHILD.COSTCENTERID,
            CHILD.COSTCENTERCODE,
            CHILD.COSTCENTERNAME,
            CHILD.PARENTCOSTCENTERID,
            PARENT.HIERARCHYLEVEL + 1,
            (PARENT.HIERARCHYPATH || ' > ' || CHILD.COSTCENTERNAME)::VARCHAR(500),
            (PARENT.SORTPATH || '/' || LPAD(CHILD.COSTCENTERID::VARCHAR, 10, '0')),
            PARENT.CUMULATIVEWEIGHT * CHILD.ALLOCATIONWEIGHT
        FROM PLANNING.COSTCENTER CHILD
        INNER JOIN HIER PARENT ON CHILD.PARENTCOSTCENTERID = PARENT.COSTCENTERID
        WHERE PARENT.HIERARCHYLEVEL < P_MAXDEPTH
          AND (P_INCLUDEINACTIVE = TRUE OR CHILD.ISACTIVE = TRUE)
          AND CHILD.EFFECTIVEFROMDATE <= NVL(P_ASOFDATE, CURRENT_DATE())
          AND (CHILD.EFFECTIVETODATE IS NULL OR CHILD.EFFECTIVETODATE >= NVL(P_ASOFDATE, CURRENT_DATE()))
    )
    SELECT
        H.COSTCENTERID,
        H.COSTCENTERCODE,
        H.COSTCENTERNAME,
        H.PARENTCOSTCENTERID,
        H.HIERARCHYLEVEL,
        H.HIERARCHYPATH,
        H.SORTPATH,
        CASE
            WHEN EXISTS (
                SELECT 1 FROM PLANNING.COSTCENTER C2
                WHERE C2.PARENTCOSTCENTERID = H.COSTCENTERID
                  AND (P_INCLUDEINACTIVE = TRUE OR C2.ISACTIVE = TRUE)
            ) THEN FALSE
            ELSE TRUE
        END AS ISLEAF,
        (SELECT COUNT(*) FROM PLANNING.COSTCENTER C3
         WHERE C3.PARENTCOSTCENTERID = H.COSTCENTERID
           AND (P_INCLUDEINACTIVE = TRUE OR C3.ISACTIVE = TRUE)) AS CHILDCOUNT,
        H.CUMULATIVEWEIGHT
    FROM HIER H
$$;
