USE DATABASE PLANNING_DB;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA PLANNING;

CREATE TABLE IF NOT EXISTS PLANNING.FISCALPERIOD (
    FISCALPERIODID          INTEGER         NOT NULL AUTOINCREMENT PRIMARY KEY,
    FISCALYEAR              SMALLINT        NOT NULL,
    FISCALQUARTER           TINYINT         NOT NULL,
    FISCALMONTH             TINYINT         NOT NULL,
    PERIODNAME              VARCHAR(50)     NOT NULL,
    PERIODSTARTDATE         DATE            NOT NULL,
    PERIODENDDATE           DATE            NOT NULL,
    ISCLOSED                BOOLEAN         NOT NULL DEFAULT FALSE,
    CLOSEDBYUSERID          INTEGER         NULL,
    CLOSEDDATETIME          TIMESTAMP_NTZ(9) NULL,
    ISADJUSTMENTPERIOD      BOOLEAN         NOT NULL DEFAULT FALSE,
    WORKINGDAYS             TINYINT         NULL,
    CREATEDDATETIME         TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFIEDDATETIME        TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (FISCALYEAR, FISCALMONTH)
);

CREATE TABLE IF NOT EXISTS PLANNING.COSTCENTER (
    COSTCENTERID            INTEGER         NOT NULL AUTOINCREMENT PRIMARY KEY,
    COSTCENTERCODE          VARCHAR(20)     NOT NULL,
    COSTCENTERNAME          VARCHAR(100)    NOT NULL,
    PARENTCOSTCENTERID      INTEGER         NULL,
    HIERARCHYPATH           VARCHAR(500)    NULL,
    HIERARCHYLEVEL          INTEGER         NULL,
    MANAGEREMPLOYEEID       INTEGER         NULL,
    DEPARTMENTCODE          VARCHAR(10)     NULL,
    ISACTIVE                BOOLEAN         NOT NULL DEFAULT TRUE,
    EFFECTIVEFROMDATE       DATE            NOT NULL,
    EFFECTIVETODATE         DATE            NULL,
    ALLOCATIONWEIGHT        NUMBER(5,4)     NOT NULL DEFAULT 1.0000,
    VALIDFROM               TIMESTAMP_NTZ(9) NULL,
    VALIDTO                 TIMESTAMP_NTZ(9) NULL,
    UNIQUE (COSTCENTERCODE),
    FOREIGN KEY (PARENTCOSTCENTERID) REFERENCES PLANNING.COSTCENTER (COSTCENTERID)
);

CREATE TABLE IF NOT EXISTS PLANNING.GLACCOUNT (
    GLACCOOUNTID            INTEGER         NOT NULL AUTOINCREMENT PRIMARY KEY,
    ACCOUNTNUMBER           VARCHAR(20)     NOT NULL,
    ACCOUNTNAME             VARCHAR(150)    NOT NULL,
    ACCOUNTTYPE             CHAR(1)         NOT NULL,
    ACCOUNTSUBTYPE          VARCHAR(30)     NULL,
    PARENTACCOUNTID         INTEGER         NULL,
    ACCOUNTLEVEL            TINYINT         NOT NULL DEFAULT 1,
    ISPOSTABLE              BOOLEAN         NOT NULL DEFAULT TRUE,
    ISBUDGETABLE            BOOLEAN         NOT NULL DEFAULT TRUE,
    ISSTATISTICAL           BOOLEAN         NOT NULL DEFAULT FALSE,
    NORMALBALANCE           CHAR(1)         NOT NULL DEFAULT 'D',
    CURRENCYCODE            CHAR(3)         NOT NULL DEFAULT 'USD',
    CONSOLIDATIONACCOUNTID  INTEGER         NULL,
    INTERCOMPANYFLAG        BOOLEAN         NOT NULL DEFAULT FALSE,
    ISACTIVE                BOOLEAN         NOT NULL DEFAULT TRUE,
    CREATEDDATETIME         TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFIEDDATETIME        TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    TAXCODE                 VARCHAR(20)     NULL,
    STATUTORYACCOUNTCODE    VARCHAR(30)     NULL,
    IFRSACCOUNTCODE         VARCHAR(30)     NULL,
    UNIQUE (ACCOUNTNUMBER),
    FOREIGN KEY (PARENTACCOUNTID) REFERENCES PLANNING.GLACCOUNT (GLACCOOUNTID)
);

CREATE TABLE IF NOT EXISTS PLANNING.BUDGETHEADER (
    BUDGETHEADERID          INTEGER         NOT NULL AUTOINCREMENT PRIMARY KEY,
    BUDGETCODE              VARCHAR(30)     NOT NULL,
    BUDGETNAME              VARCHAR(100)    NOT NULL,
    BUDGETTYPE              VARCHAR(20)     NOT NULL,
    SCENARIOTYPE            VARCHAR(20)     NOT NULL,
    FISCALYEAR              SMALLINT        NOT NULL,
    STARTPERIODID           INTEGER         NOT NULL,
    ENDPERIODID             INTEGER         NOT NULL,
    BASEBUDGETHEADERID      INTEGER         NULL,
    STATUSCODE              VARCHAR(15)     NOT NULL DEFAULT 'DRAFT',
    SUBMITTEDBYUSERID       INTEGER         NULL,
    SUBMITTEDDATETIME       TIMESTAMP_NTZ(9) NULL,
    APPROVEDBYUSERID        INTEGER         NULL,
    APPROVEDDATETIME        TIMESTAMP_NTZ(9) NULL,
    LOCKEDDATETIME          TIMESTAMP_NTZ(9) NULL,
    ISLOCKED                BOOLEAN         NOT NULL DEFAULT FALSE,
    VERSIONNUMBER           INTEGER         NOT NULL DEFAULT 1,
    NOTES                   VARCHAR(16777216) NULL,
    EXTENDEDPROPERTIES      VARIANT         NULL,
    CREATEDDATETIME         TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFIEDDATETIME        TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (BUDGETCODE, FISCALYEAR, VERSIONNUMBER),
    FOREIGN KEY (STARTPERIODID)     REFERENCES PLANNING.FISCALPERIOD (FISCALPERIODID),
    FOREIGN KEY (ENDPERIODID)       REFERENCES PLANNING.FISCALPERIOD (FISCALPERIODID),
    FOREIGN KEY (BASEBUDGETHEADERID) REFERENCES PLANNING.BUDGETHEADER (BUDGETHEADERID)
);

CREATE TABLE IF NOT EXISTS PLANNING.ALLOCATIONRULE (
    ALLOCATIONRULEID        INTEGER         NOT NULL AUTOINCREMENT PRIMARY KEY,
    RULECODE                VARCHAR(30)     NOT NULL,
    RULENAME                VARCHAR(100)    NOT NULL,
    RULEDESCRIPTION         VARCHAR(500)    NULL,
    RULETYPE                VARCHAR(20)     NOT NULL,
    ALLOCATIONMETHOD        VARCHAR(20)     NOT NULL,
    SOURCECOSTCENTERID      INTEGER         NULL,
    SOURCECOSTCENTERPATTERN VARCHAR(50)     NULL,
    SOURCEACCOUNTPATTERN    VARCHAR(50)     NULL,
    TARGETSPECIFICATION     VARIANT         NOT NULL,
    ALLOCATIONBASIS         VARCHAR(30)     NULL,
    ALLOCATIONPERCENTAGE    NUMBER(8,6)     NULL,
    ROUNDINGMETHOD          VARCHAR(10)     NOT NULL DEFAULT 'NEAREST',
    ROUNDINGPRECISION       TINYINT         NOT NULL DEFAULT 2,
    MINIMUMAMOUNT           NUMBER(19,4)    NULL,
    EXECUTIONSEQUENCE       INTEGER         NOT NULL DEFAULT 100,
    DEPENDSONRULEID         INTEGER         NULL,
    EFFECTIVEFROMDATE       DATE            NOT NULL,
    EFFECTIVETODATE         DATE            NULL,
    ISACTIVE                BOOLEAN         NOT NULL DEFAULT TRUE,
    CREATEDBYUSERID         INTEGER         NULL,
    CREATEDDATETIME         TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFIEDBYUSERID        INTEGER         NULL,
    MODIFIEDDATETIME        TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (RULECODE),
    FOREIGN KEY (SOURCECOSTCENTERID) REFERENCES PLANNING.COSTCENTER (COSTCENTERID),
    FOREIGN KEY (DEPENDSONRULEID)    REFERENCES PLANNING.ALLOCATIONRULE (ALLOCATIONRULEID)
);

CREATE TABLE IF NOT EXISTS PLANNING.BUDGETLINEITEM (
    BUDGETLINEITEMID        BIGINT          NOT NULL AUTOINCREMENT PRIMARY KEY,
    BUDGETHEADERID          INTEGER         NOT NULL,
    GLACCOOUNTID            INTEGER         NOT NULL,
    COSTCENTERID            INTEGER         NOT NULL,
    FISCALPERIODID          INTEGER         NOT NULL,
    ORIGINALAMOUNT          NUMBER(19,4)    NOT NULL DEFAULT 0,
    ADJUSTEDAMOUNT          NUMBER(19,4)    NOT NULL DEFAULT 0,
    FINALAMOUNT             NUMBER(19,4)    NULL,
    LOCALCURRENCYAMOUNT     NUMBER(19,4)    NULL,
    REPORTINGCURRENCYAMOUNT NUMBER(19,4)    NULL,
    STATISTICALQUANTITY     NUMBER(18,6)    NULL,
    UNITOFMEASURE           VARCHAR(10)     NULL,
    SPREADMETHODCODE        VARCHAR(30)     NULL,
    SEASONALITYFACTOR       NUMBER(8,6)     NULL,
    SOURCESYSTEM            VARCHAR(30)     NULL,
    SOURCEREFERENCE         VARCHAR(100)    NULL,
    IMPORTBATCHID           VARCHAR(36)     NULL,
    ISALLOCATED             BOOLEAN         NOT NULL DEFAULT FALSE,
    ALLOCATIONSOURCELINEID  BIGINT          NULL,
    ALLOCATIONPERCENTAGE    NUMBER(8,6)     NULL,
    LASTMODIFIEDBYUSERID    INTEGER         NULL,
    LASTMODIFIEDDATETIME    TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (BUDGETHEADERID)       REFERENCES PLANNING.BUDGETHEADER (BUDGETHEADERID),
    FOREIGN KEY (GLACCOOUNTID)         REFERENCES PLANNING.GLACCOUNT (GLACCOOUNTID),
    FOREIGN KEY (COSTCENTERID)         REFERENCES PLANNING.COSTCENTER (COSTCENTERID),
    FOREIGN KEY (FISCALPERIODID)       REFERENCES PLANNING.FISCALPERIOD (FISCALPERIODID),
    FOREIGN KEY (ALLOCATIONSOURCELINEID) REFERENCES PLANNING.BUDGETLINEITEM (BUDGETLINEITEMID)
);

ALTER TABLE PLANNING.BUDGETLINEITEM ADD CONSTRAINT UQ_BUDGETLINEITEM_NATURALKEY
    UNIQUE (BUDGETHEADERID, GLACCOOUNTID, COSTCENTERID, FISCALPERIODID);

CREATE TABLE IF NOT EXISTS PLANNING.CONSOLIDATIONJOURNAL (
    JOURNALID               BIGINT          NOT NULL AUTOINCREMENT PRIMARY KEY,
    JOURNALNUMBER           VARCHAR(50)     NOT NULL,
    JOURNALTYPE             VARCHAR(30)     NOT NULL,
    BUDGETHEADERID          INTEGER         NOT NULL,
    FISCALPERIODID          INTEGER         NOT NULL,
    POSTINGDATE             DATE            NOT NULL,
    DESCRIPTION             VARCHAR(500)    NULL,
    STATUSCODE              VARCHAR(20)     NOT NULL DEFAULT 'DRAFT',
    SUPPORTINGDOCUMENTREF   VARCHAR(500)    NULL,
    JOURNALGUID             VARCHAR(36)     NOT NULL DEFAULT UUID_STRING(),
    CREATEDDATETIME         TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFIEDDATETIME        TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (JOURNALNUMBER),
    FOREIGN KEY (BUDGETHEADERID)  REFERENCES PLANNING.BUDGETHEADER (BUDGETHEADERID),
    FOREIGN KEY (FISCALPERIODID)  REFERENCES PLANNING.FISCALPERIOD (FISCALPERIODID)
);

CREATE TABLE IF NOT EXISTS PLANNING.CONSOLIDATIONJOURNALLINE (
    JOURNALLINEID           BIGINT          NOT NULL AUTOINCREMENT PRIMARY KEY,
    JOURNALID               BIGINT          NOT NULL,
    LINENUMBER              INTEGER         NOT NULL,
    GLACCOOUNTID            INTEGER         NOT NULL,
    COSTCENTERID            INTEGER         NOT NULL,
    ALLOCATIONRULEID        INTEGER         NULL,
    DEBITAMOUNT             NUMBER(19,4)    NOT NULL DEFAULT 0,
    CREDITAMOUNT            NUMBER(19,4)    NOT NULL DEFAULT 0,
    DESCRIPTION             VARCHAR(500)    NULL,
    CREATEDDATETIME         TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (JOURNALID)       REFERENCES PLANNING.CONSOLIDATIONJOURNAL (JOURNALID),
    FOREIGN KEY (GLACCOOUNTID)    REFERENCES PLANNING.GLACCOUNT (GLACCOOUNTID),
    FOREIGN KEY (COSTCENTERID)    REFERENCES PLANNING.COSTCENTER (COSTCENTERID),
    FOREIGN KEY (ALLOCATIONRULEID) REFERENCES PLANNING.ALLOCATIONRULE (ALLOCATIONRULEID)
);
