USE DATABASE PLANNING_DB;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA PLANNING;

CREATE OR REPLACE PROCEDURE PLANNING.USP_RECONCILEINTERCOMPANYBALANCES (
    BUDGET_HEADER_ID        INTEGER,
    RECONCILIATION_DATE     DATE         DEFAULT NULL,
    ENTITY_CODES            VARIANT      DEFAULT NULL,
    TOLERANCE_AMOUNT        NUMBER(19,4) DEFAULT 0.01,
    TOLERANCE_PERCENT       NUMBER(5,4)  DEFAULT 0.001,
    AUTO_CREATE_ADJUSTMENTS BOOLEAN      DEFAULT FALSE
)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DECLARE
    v_run_id         VARCHAR      := UUID_STRING();
    v_eff_date       DATE         := NVL(RECONCILIATION_DATE, CURRENT_DATE());
    v_unreconciled   INTEGER      := 0;
    v_total_variance NUMBER(19,4) := 0;
    v_journal_id     BIGINT       := 0;
    v_header_exists  INTEGER      := 0;

BEGIN
    v_header_exists := (
        SELECT COUNT(*) FROM PLANNING.BUDGETHEADER
        WHERE BUDGETHEADERID = :BUDGET_HEADER_ID
    );

    IF (v_header_exists = 0) THEN
        RETURN OBJECT_CONSTRUCT(
            'STATUS',             'ERROR',
            'ERROR_MESSAGE',      'Budget header not found: ' || BUDGET_HEADER_ID::VARCHAR,
            'UNRECONCILED_COUNT', 0,
            'TOTAL_VARIANCE',     0
        )::VARIANT;
    END IF;

    BEGIN TRANSACTION;

    CREATE OR REPLACE TEMPORARY TABLE TEMP_IC_PAIRS (
        PAIRID              INTEGER      NOT NULL AUTOINCREMENT PRIMARY KEY,
        GLACCOOUNTID        INTEGER      NOT NULL,
        PARTNERACCOUNTID    INTEGER      NULL,
        ENTITY1AMOUNT       NUMBER(19,4) NOT NULL,
        ENTITY2AMOUNT       NUMBER(19,4) NOT NULL DEFAULT 0,
        VARIANCE            NUMBER(19,4) NOT NULL,
        ISWITHINTOLERANCE   BOOLEAN      NOT NULL,
        RECONCILIATIONSTATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING'
    );

    INSERT INTO TEMP_IC_PAIRS (
        GLACCOOUNTID, PARTNERACCOUNTID,
        ENTITY1AMOUNT, ENTITY2AMOUNT, VARIANCE, ISWITHINTOLERANCE
    )
    SELECT
        BLI1.GLACCOOUNTID,
        GLA1.CONSOLIDATIONACCOUNTID,
        SUM(BLI1.FINALAMOUNT),
        -SUM(NVL(BLI2.FINALAMOUNT, 0)),
        SUM(BLI1.FINALAMOUNT) + SUM(NVL(BLI2.FINALAMOUNT, 0)),
        CASE
            WHEN ABS(SUM(BLI1.FINALAMOUNT) + SUM(NVL(BLI2.FINALAMOUNT, 0))) <= :TOLERANCE_AMOUNT
            THEN TRUE
            WHEN ABS(SUM(BLI1.FINALAMOUNT)) > 0
                 AND ABS((SUM(BLI1.FINALAMOUNT) + SUM(NVL(BLI2.FINALAMOUNT, 0)))
                         / SUM(BLI1.FINALAMOUNT)) <= :TOLERANCE_PERCENT
            THEN TRUE
            ELSE FALSE
        END
    FROM PLANNING.BUDGETLINEITEM BLI1
    INNER JOIN PLANNING.GLACCOUNT GLA1 ON BLI1.GLACCOOUNTID = GLA1.GLACCOOUNTID
    LEFT JOIN PLANNING.BUDGETLINEITEM BLI2
        ON BLI2.BUDGETHEADERID = :BUDGET_HEADER_ID
       AND BLI2.GLACCOOUNTID  = GLA1.CONSOLIDATIONACCOUNTID
    WHERE BLI1.BUDGETHEADERID = :BUDGET_HEADER_ID
      AND GLA1.INTERCOMPANYFLAG = TRUE
      AND GLA1.CONSOLIDATIONACCOUNTID IS NOT NULL
    GROUP BY BLI1.GLACCOOUNTID, GLA1.CONSOLIDATIONACCOUNTID
    HAVING SUM(BLI1.FINALAMOUNT) <> 0 OR SUM(NVL(BLI2.FINALAMOUNT, 0)) <> 0;

    UPDATE TEMP_IC_PAIRS
    SET RECONCILIATIONSTATUS = CASE
        WHEN ISWITHINTOLERANCE = TRUE     THEN 'RECONCILED'
        WHEN ABS(VARIANCE) <= :TOLERANCE_AMOUNT THEN 'MATCHED'
        ELSE 'UNRECONCILED'
    END;

    v_unreconciled := (
        SELECT COUNT(*) FROM TEMP_IC_PAIRS
        WHERE RECONCILIATIONSTATUS = 'UNRECONCILED'
    );

    v_total_variance := (
        SELECT NVL(SUM(ABS(VARIANCE)), 0) FROM TEMP_IC_PAIRS
        WHERE RECONCILIATIONSTATUS = 'UNRECONCILED'
    );

    IF (AUTO_CREATE_ADJUSTMENTS AND v_unreconciled > 0) THEN
        INSERT INTO PLANNING.CONSOLIDATIONJOURNAL (
            JOURNALNUMBER, JOURNALTYPE, BUDGETHEADERID, FISCALPERIODID,
            POSTINGDATE, DESCRIPTION, STATUSCODE
        )
        SELECT
            'ICR-' || TO_CHAR(:v_eff_date, 'YYYYMMDD') || '-' || LEFT(:v_run_id, 8),
            'ELIMINATION',
            :BUDGET_HEADER_ID,
            FP.FISCALPERIODID,
            :v_eff_date,
            'Auto intercompany reconciliation adjustment',
            'DRAFT'
        FROM PLANNING.FISCALPERIOD FP
        WHERE :v_eff_date BETWEEN FP.PERIODSTARTDATE AND FP.PERIODENDDATE
        LIMIT 1;

        v_journal_id := (
            SELECT MAX(JOURNALID) FROM PLANNING.CONSOLIDATIONJOURNAL
            WHERE BUDGETHEADERID = :BUDGET_HEADER_ID
              AND STATUSCODE = 'DRAFT'
        );

        INSERT INTO PLANNING.CONSOLIDATIONJOURNALLINE (
            JOURNALID, LINENUMBER, GLACCOOUNTID, COSTCENTERID,
            DEBITAMOUNT, CREDITAMOUNT, DESCRIPTION
        )
        SELECT
            :v_journal_id,
            ROW_NUMBER() OVER (ORDER BY IP.PAIRID),
            IP.GLACCOOUNTID,
            (SELECT MIN(COSTCENTERID) FROM PLANNING.BUDGETLINEITEM
             WHERE BUDGETHEADERID = :BUDGET_HEADER_ID
               AND GLACCOOUNTID   = IP.GLACCOOUNTID),
            CASE WHEN IP.VARIANCE > 0 THEN IP.VARIANCE ELSE 0 END,
            CASE WHEN IP.VARIANCE < 0 THEN ABS(IP.VARIANCE) ELSE 0 END,
            'IC Adjustment account ' || IP.GLACCOOUNTID::VARCHAR
        FROM TEMP_IC_PAIRS IP
        WHERE IP.RECONCILIATIONSTATUS = 'UNRECONCILED'
          AND ABS(IP.VARIANCE) > :TOLERANCE_AMOUNT;
    END IF;

    COMMIT;

    LET v_report VARIANT := (
        SELECT OBJECT_CONSTRUCT(
            'ReconciliationID',  :v_run_id,
            'BudgetHeaderID',    :BUDGET_HEADER_ID,
            'EffectiveDate',     :v_eff_date::VARCHAR,
            'TotalPairs',        COUNT(*),
            'ReconciledPairs',   COUNT_IF(RECONCILIATIONSTATUS = 'RECONCILED'),
            'UnreconciledPairs', COUNT_IF(RECONCILIATIONSTATUS = 'UNRECONCILED'),
            'TotalVariance',     NVL(SUM(ABS(VARIANCE)), 0)
        )
        FROM TEMP_IC_PAIRS
    );

    DROP TABLE IF EXISTS TEMP_IC_PAIRS;

    RETURN OBJECT_CONSTRUCT(
        'STATUS',             'COMPLETED',
        'UNRECONCILED_COUNT', v_unreconciled,
        'TOTAL_VARIANCE',     v_total_variance,
        'REPORT',             v_report,
        'RUN_ID',             v_run_id
    )::VARIANT;

EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        DROP TABLE IF EXISTS TEMP_IC_PAIRS;
        RETURN OBJECT_CONSTRUCT(
            'STATUS',             'ERROR',
            'ERROR_MESSAGE',      SQLERRM,
            'UNRECONCILED_COUNT', 0,
            'TOTAL_VARIANCE',     0
        )::VARIANT;
END;
$$;
