USE DATABASE PLANNING_DB;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA PLANNING;

CREATE OR REPLACE PROCEDURE PLANNING.USP_EXECUTECOSTALLOCATION (
    BUDGET_HEADER_ID    INTEGER,
    ALLOCATION_RULE_IDS VARIANT  DEFAULT NULL,
    P_FISCAL_PERIOD_ID  INTEGER  DEFAULT NULL,
    DRY_RUN             BOOLEAN  DEFAULT FALSE,
    MAX_ITERATIONS      INTEGER  DEFAULT 100
)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DECLARE
    v_run_id         VARCHAR  := UUID_STRING();
    v_rows_allocated INTEGER  := 0;
    v_iteration      INTEGER  := 0;
    v_batch_rows     INTEGER  := 1;
    v_warnings       ARRAY    := ARRAY_CONSTRUCT();
    v_header_exists  INTEGER  := 0;

BEGIN
    v_header_exists := (
        SELECT COUNT(*) FROM PLANNING.BUDGETHEADER
        WHERE BUDGETHEADERID = :BUDGET_HEADER_ID
    );

    IF (v_header_exists = 0) THEN
        RETURN OBJECT_CONSTRUCT(
            'STATUS',           'ERROR',
            'ERROR_MESSAGE',    'Budget header not found: ' || BUDGET_HEADER_ID::VARCHAR,
            'ROWS_ALLOCATED',   0
        )::VARIANT;
    END IF;

    BEGIN TRANSACTION;

    CREATE OR REPLACE TEMPORARY TABLE TEMP_ALLOC_QUEUE (
        QUEUEID             INTEGER      NOT NULL AUTOINCREMENT PRIMARY KEY,
        ALLOCATIONRULEID    INTEGER      NOT NULL,
        SRCBUDGETLINEITEMID BIGINT       NOT NULL,
        SRCAMOUNT           NUMBER(19,4) NOT NULL,
        REMAININGAMOUNT     NUMBER(19,4) NOT NULL,
        EXECUTIONSEQUENCE   INTEGER      NOT NULL,
        DEPENDSONRULEID     INTEGER      NULL,
        ISPROCESSED         BOOLEAN      DEFAULT FALSE
    );

    INSERT INTO TEMP_ALLOC_QUEUE (
        ALLOCATIONRULEID, SRCBUDGETLINEITEMID, SRCAMOUNT,
        REMAININGAMOUNT, EXECUTIONSEQUENCE, DEPENDSONRULEID
    )
    SELECT
        AR.ALLOCATIONRULEID,
        BLI.BUDGETLINEITEMID,
        NVL(BLI.FINALAMOUNT, BLI.ORIGINALAMOUNT + BLI.ADJUSTEDAMOUNT),
        NVL(BLI.FINALAMOUNT, BLI.ORIGINALAMOUNT + BLI.ADJUSTEDAMOUNT),
        AR.EXECUTIONSEQUENCE,
        AR.DEPENDSONRULEID
    FROM PLANNING.ALLOCATIONRULE AR
    INNER JOIN PLANNING.BUDGETLINEITEM BLI
        ON BLI.BUDGETHEADERID = :BUDGET_HEADER_ID
       AND (:P_FISCAL_PERIOD_ID IS NULL OR BLI.FISCALPERIODID = :P_FISCAL_PERIOD_ID)
       AND (AR.SOURCECOSTCENTERID IS NULL OR BLI.COSTCENTERID = AR.SOURCECOSTCENTERID)
       AND NVL(BLI.FINALAMOUNT, BLI.ORIGINALAMOUNT + BLI.ADJUSTEDAMOUNT) <> 0
       AND BLI.ISALLOCATED = FALSE
    WHERE AR.ISACTIVE = TRUE
      AND CURRENT_DATE() >= AR.EFFECTIVEFROMDATE
      AND (AR.EFFECTIVETODATE IS NULL OR CURRENT_DATE() <= AR.EFFECTIVETODATE)
      AND (:ALLOCATION_RULE_IDS IS NULL
           OR ARRAY_CONTAINS(AR.ALLOCATIONRULEID::VARIANT, :ALLOCATION_RULE_IDS));

    CREATE OR REPLACE TEMPORARY TABLE TEMP_ALLOC_RESULTS (
        SRCBUDGETLINEITEMID BIGINT       NOT NULL,
        TGTCOSTCENTERID     INTEGER      NOT NULL,
        TGTGLACCOUNTID      INTEGER      NOT NULL,
        ALLOCATEDAMOUNT     NUMBER(19,4) NOT NULL,
        ALLOCATIONPCT       NUMBER(8,6)  NOT NULL,
        ALLOCATIONRULEID    INTEGER      NOT NULL,
        ITERATIONNUMBER     INTEGER      NOT NULL
    );

    WHILE (v_batch_rows > 0 AND v_iteration < MAX_ITERATIONS) DO
        v_iteration  := v_iteration + 1;
        v_batch_rows := 0;

        UPDATE TEMP_ALLOC_QUEUE
        SET ISPROCESSED = TRUE
        WHERE ISPROCESSED = FALSE
          AND (DEPENDSONRULEID IS NULL
               OR DEPENDSONRULEID IN (
                   SELECT DISTINCT ALLOCATIONRULEID FROM TEMP_ALLOC_RESULTS
               ));

        v_batch_rows := SQLROWCOUNT;

        IF (v_batch_rows > 0) THEN
            INSERT INTO TEMP_ALLOC_RESULTS (
                SRCBUDGETLINEITEMID, TGTCOSTCENTERID, TGTGLACCOUNTID,
                ALLOCATEDAMOUNT, ALLOCATIONPCT, ALLOCATIONRULEID, ITERATIONNUMBER
            )
            SELECT
                Q.SRCBUDGETLINEITEMID,
                VT.TARGETCOSTCENTERID,
                BLI.GLACCOOUNTID,
                ROUND(
                    Q.REMAININGAMOUNT * PLANNING.FN_GETALLOCATIONFACTOR(
                        BLI.COSTCENTERID, VT.TARGETCOSTCENTERID,
                        AR.ALLOCATIONBASIS, BLI.FISCALPERIODID, :BUDGET_HEADER_ID
                    ), 2
                ),
                NVL(
                    VT.TARGETALLOCATIONPCT,
                    PLANNING.FN_GETALLOCATIONFACTOR(
                        BLI.COSTCENTERID, VT.TARGETCOSTCENTERID,
                        AR.ALLOCATIONBASIS, BLI.FISCALPERIODID, :BUDGET_HEADER_ID
                    )
                ),
                Q.ALLOCATIONRULEID,
                :v_iteration
            FROM TEMP_ALLOC_QUEUE Q
            INNER JOIN PLANNING.ALLOCATIONRULE AR   ON Q.ALLOCATIONRULEID    = AR.ALLOCATIONRULEID
            INNER JOIN PLANNING.BUDGETLINEITEM BLI   ON Q.SRCBUDGETLINEITEMID = BLI.BUDGETLINEITEMID
            INNER JOIN PLANNING.VW_ALLOCATIONRULETARGETS VT
                ON VT.ALLOCATIONRULEID = AR.ALLOCATIONRULEID
               AND VT.TARGETISACTIVE   = TRUE
            WHERE Q.ISPROCESSED = TRUE;
        END IF;
    END WHILE;

    IF (v_iteration >= MAX_ITERATIONS) THEN
        v_warnings := ARRAY_APPEND(v_warnings,
            'Max iterations (' || MAX_ITERATIONS::VARCHAR || ') reached.');
    END IF;

    IF (NOT DRY_RUN) THEN
        INSERT INTO PLANNING.BUDGETLINEITEM (
            BUDGETHEADERID, GLACCOOUNTID, COSTCENTERID, FISCALPERIODID,
            ORIGINALAMOUNT, ADJUSTEDAMOUNT, ISALLOCATED,
            ALLOCATIONSOURCELINEID, ALLOCATIONPERCENTAGE, LASTMODIFIEDDATETIME
        )
        SELECT
            :BUDGET_HEADER_ID,
            R.TGTGLACCOUNTID,
            R.TGTCOSTCENTERID,
            BLI.FISCALPERIODID,
            R.ALLOCATEDAMOUNT,
            0,
            TRUE,
            R.SRCBUDGETLINEITEMID,
            R.ALLOCATIONPCT,
            CURRENT_TIMESTAMP()
        FROM TEMP_ALLOC_RESULTS R
        INNER JOIN PLANNING.BUDGETLINEITEM BLI ON R.SRCBUDGETLINEITEMID = BLI.BUDGETLINEITEMID;

        v_rows_allocated := SQLROWCOUNT;

        UPDATE PLANNING.BUDGETLINEITEM
        SET ISALLOCATED = TRUE,
            LASTMODIFIEDDATETIME = CURRENT_TIMESTAMP()
        WHERE BUDGETLINEITEMID IN (
            SELECT DISTINCT SRCBUDGETLINEITEMID FROM TEMP_ALLOC_RESULTS
        );
    ELSE
        v_rows_allocated := (SELECT COUNT(*) FROM TEMP_ALLOC_RESULTS);
    END IF;

    COMMIT;

    DROP TABLE IF EXISTS TEMP_ALLOC_QUEUE;
    DROP TABLE IF EXISTS TEMP_ALLOC_RESULTS;

    RETURN OBJECT_CONSTRUCT(
        'STATUS',           'COMPLETED',
        'ROWS_ALLOCATED',   v_rows_allocated,
        'ITERATIONS',       v_iteration,
        'DRY_RUN',          DRY_RUN,
        'WARNING_MESSAGES', v_warnings,
        'RUN_ID',           v_run_id
    )::VARIANT;

EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        DROP TABLE IF EXISTS TEMP_ALLOC_QUEUE;
        DROP TABLE IF EXISTS TEMP_ALLOC_RESULTS;
        RETURN OBJECT_CONSTRUCT(
            'STATUS',         'ERROR',
            'ERROR_MESSAGE',  SQLERRM,
            'ROWS_ALLOCATED', 0
        )::VARIANT;
END;
$$;
