USE DATABASE PLANNING_DB;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA PLANNING;

CREATE OR REPLACE PROCEDURE PLANNING.USP_GENERATEROLLINGFORECAST (
    BASE_BUDGET_HEADER_ID INTEGER,
    HISTORICAL_PERIODS    INTEGER    DEFAULT 12,
    FORECAST_PERIODS      INTEGER    DEFAULT 12,
    FORECAST_METHOD       VARCHAR    DEFAULT 'WEIGHTED_AVERAGE',
    SEASONALITY_JSON      VARIANT    DEFAULT NULL,
    GROWTH_RATE_OVERRIDE  NUMBER(8,4) DEFAULT NULL,
    OUTPUT_FORMAT         VARCHAR    DEFAULT 'DETAIL'
)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DECLARE
    v_run_id          VARCHAR  := UUID_STRING();
    v_target_id       INTEGER  := 0;
    v_rows_forecast   INTEGER  := 0;
    v_fiscal_year     SMALLINT := 0;
    v_start_period_id INTEGER  := 0;
    v_base_exists     INTEGER  := 0;

BEGIN
    v_base_exists := (
        SELECT COUNT(*) FROM PLANNING.BUDGETHEADER
        WHERE BUDGETHEADERID = :BASE_BUDGET_HEADER_ID
    );

    IF (v_base_exists = 0) THEN
        RETURN OBJECT_CONSTRUCT(
            'STATUS',                  'ERROR',
            'ERROR_MESSAGE',           'Base budget header not found: ' || BASE_BUDGET_HEADER_ID::VARCHAR,
            'TARGET_BUDGET_HEADER_ID', NULL,
            'ROWS_FORECAST',           0
        )::VARIANT;
    END IF;

    v_fiscal_year := (
        SELECT FISCALYEAR FROM PLANNING.BUDGETHEADER
        WHERE BUDGETHEADERID = :BASE_BUDGET_HEADER_ID
    );

    v_start_period_id := (
        SELECT STARTPERIODID FROM PLANNING.BUDGETHEADER
        WHERE BUDGETHEADERID = :BASE_BUDGET_HEADER_ID
    );

    BEGIN TRANSACTION;

    CREATE OR REPLACE TEMPORARY TABLE TEMP_FORECAST_WRK (
        GLACCOOUNTID   INTEGER      NOT NULL,
        COSTCENTERID   INTEGER      NOT NULL,
        FISCALPERIODID INTEGER      NOT NULL,
        PERIODSEQUENCE INTEGER      NOT NULL,
        ACTUALAMOUNT   NUMBER(19,4),
        FORECASTAMOUNT NUMBER(19,4),
        WEIGHTFACTOR   NUMBER(8,6),
        LOWERBOUND     NUMBER(19,4),
        UPPERBOUND     NUMBER(19,4),
        ISFORECAST     BOOLEAN      DEFAULT FALSE
    );

    INSERT INTO TEMP_FORECAST_WRK (
        GLACCOOUNTID, COSTCENTERID, FISCALPERIODID, PERIODSEQUENCE,
        ACTUALAMOUNT, WEIGHTFACTOR, ISFORECAST
    )
    SELECT
        BLI.GLACCOOUNTID,
        BLI.COSTCENTERID,
        BLI.FISCALPERIODID,
        ROW_NUMBER() OVER (
            PARTITION BY BLI.GLACCOOUNTID, BLI.COSTCENTERID
            ORDER BY FP.FISCALYEAR, FP.FISCALMONTH
        ),
        NVL(BLI.FINALAMOUNT, BLI.ORIGINALAMOUNT + BLI.ADJUSTEDAMOUNT),
        POWER(0.9, :HISTORICAL_PERIODS - ROW_NUMBER() OVER (
            PARTITION BY BLI.GLACCOOUNTID, BLI.COSTCENTERID
            ORDER BY FP.FISCALYEAR, FP.FISCALMONTH
        )),
        FALSE
    FROM PLANNING.BUDGETLINEITEM BLI
    INNER JOIN PLANNING.FISCALPERIOD FP ON BLI.FISCALPERIODID = FP.FISCALPERIODID
    WHERE BLI.BUDGETHEADERID = :BASE_BUDGET_HEADER_ID
      AND FP.FISCALYEAR >= :v_fiscal_year - 1;

    INSERT INTO TEMP_FORECAST_WRK (
        GLACCOOUNTID, COSTCENTERID, FISCALPERIODID, PERIODSEQUENCE,
        FORECASTAMOUNT, LOWERBOUND, UPPERBOUND, ISFORECAST
    )
    WITH BASELINE AS (
        SELECT
            GLACCOOUNTID,
            COSTCENTERID,
            MAX(PERIODSEQUENCE) AS LASTSEQ,
            SUM(ACTUALAMOUNT * WEIGHTFACTOR) / NULLIF(SUM(WEIGHTFACTOR), 0) AS WEIGHTEDAVG,
            STDDEV(ACTUALAMOUNT) AS STDDEV_AMT
        FROM TEMP_FORECAST_WRK
        WHERE ISFORECAST = FALSE
        GROUP BY GLACCOOUNTID, COSTCENTERID
    ),
    FUTURE AS (
        SELECT
            FP.FISCALPERIODID,
            ROW_NUMBER() OVER (ORDER BY FP.FISCALYEAR, FP.FISCALMONTH) AS FUTSEQ
        FROM PLANNING.FISCALPERIOD FP
        WHERE FP.FISCALPERIODID > (
            SELECT MAX(FISCALPERIODID) FROM TEMP_FORECAST_WRK WHERE ISFORECAST = FALSE
        )
          AND FP.ISCLOSED = FALSE
    )
    SELECT
        B.GLACCOOUNTID,
        B.COSTCENTERID,
        F.FISCALPERIODID,
        B.LASTSEQ + F.FUTSEQ,
        CASE :FORECAST_METHOD
            WHEN 'LINEAR_TREND' THEN
                B.WEIGHTEDAVG + (NVL(:GROWTH_RATE_OVERRIDE, 0.02) * (B.LASTSEQ + F.FUTSEQ))
            WHEN 'EXPONENTIAL' THEN
                B.WEIGHTEDAVG * POWER(1 + NVL(:GROWTH_RATE_OVERRIDE, 0.02), F.FUTSEQ)
            ELSE
                B.WEIGHTEDAVG * POWER(1 + NVL(:GROWTH_RATE_OVERRIDE, 0.02), F.FUTSEQ)
        END,
        B.WEIGHTEDAVG - (1.96 * NVL(B.STDDEV_AMT, 0) * SQRT(F.FUTSEQ)),
        B.WEIGHTEDAVG + (1.96 * NVL(B.STDDEV_AMT, 0) * SQRT(F.FUTSEQ)),
        TRUE
    FROM BASELINE B
    CROSS JOIN FUTURE F
    WHERE F.FUTSEQ <= :FORECAST_PERIODS;

    INSERT INTO PLANNING.BUDGETHEADER (
        BUDGETCODE, BUDGETNAME, BUDGETTYPE, SCENARIOTYPE, FISCALYEAR,
        STARTPERIODID, ENDPERIODID, BASEBUDGETHEADERID, STATUSCODE
    )
    SELECT
        BUDGETCODE || '_FORECAST_' || TO_CHAR(CURRENT_DATE(), 'YYYYMMDD'),
        BUDGETNAME || ' - Rolling Forecast',
        'ROLLING',
        'FORECAST',
        FISCALYEAR,
        :v_start_period_id,
        (SELECT MAX(FISCALPERIODID) FROM TEMP_FORECAST_WRK WHERE ISFORECAST = TRUE),
        :BASE_BUDGET_HEADER_ID,
        'DRAFT'
    FROM PLANNING.BUDGETHEADER
    WHERE BUDGETHEADERID = :BASE_BUDGET_HEADER_ID;

    v_target_id := (
        SELECT MAX(BUDGETHEADERID) FROM PLANNING.BUDGETHEADER
        WHERE BASEBUDGETHEADERID = :BASE_BUDGET_HEADER_ID
          AND BUDGETTYPE = 'ROLLING'
    );

    INSERT INTO PLANNING.BUDGETLINEITEM (
        BUDGETHEADERID, GLACCOOUNTID, COSTCENTERID, FISCALPERIODID,
        ORIGINALAMOUNT, ADJUSTEDAMOUNT, SPREADMETHODCODE, SOURCESYSTEM
    )
    SELECT
        :v_target_id,
        GLACCOOUNTID,
        COSTCENTERID,
        FISCALPERIODID,
        FORECASTAMOUNT,
        0,
        :FORECAST_METHOD,
        'ROLLING_FORECAST'
    FROM TEMP_FORECAST_WRK
    WHERE ISFORECAST = TRUE
      AND FORECASTAMOUNT IS NOT NULL;

    v_rows_forecast := SQLROWCOUNT;

    COMMIT;

    DROP TABLE IF EXISTS TEMP_FORECAST_WRK;

    RETURN OBJECT_CONSTRUCT(
        'STATUS',                  'COMPLETED',
        'TARGET_BUDGET_HEADER_ID', v_target_id,
        'ROWS_FORECAST',           v_rows_forecast,
        'FORECAST_METHOD',         FORECAST_METHOD,
        'FORECAST_PERIODS',        FORECAST_PERIODS,
        'RUN_ID',                  v_run_id
    )::VARIANT;

EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        DROP TABLE IF EXISTS TEMP_FORECAST_WRK;
        RETURN OBJECT_CONSTRUCT(
            'STATUS',                  'ERROR',
            'ERROR_MESSAGE',           SQLERRM,
            'TARGET_BUDGET_HEADER_ID', NULL,
            'ROWS_FORECAST',           0
        )::VARIANT;
END;
$$;
