USE DATABASE PLANNING_DB;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA PLANNING;

CREATE OR REPLACE PROCEDURE PLANNING.USP_BULKIMPORTBUDGETDATA (
    IMPORT_SOURCE           VARCHAR,
    TARGET_BUDGET_HEADER_ID INTEGER,
    STAGE_PATH              VARCHAR  DEFAULT NULL,
    STAGING_TABLE_NAME      VARCHAR  DEFAULT NULL,
    VALIDATION_MODE         VARCHAR  DEFAULT 'STRICT',
    DUPLICATE_HANDLING      VARCHAR  DEFAULT 'REJECT',
    BATCH_SIZE              INTEGER  DEFAULT 10000
)
RETURNS VARIANT
LANGUAGE SQL
AS
$$
DECLARE
    v_run_id         VARCHAR  := UUID_STRING();
    v_total_rows     INTEGER  := 0;
    v_valid_rows     INTEGER  := 0;
    v_invalid_rows   INTEGER  := 0;
    v_imported_rows  INTEGER  := 0;
    v_skipped_rows   INTEGER  := 0;
    v_header_exists  INTEGER  := 0;
    v_dyn_sql        VARCHAR  := '';

BEGIN
    v_header_exists := (
        SELECT COUNT(*) FROM PLANNING.BUDGETHEADER
        WHERE BUDGETHEADERID = :TARGET_BUDGET_HEADER_ID
    );

    IF (v_header_exists = 0 OR :TARGET_BUDGET_HEADER_ID IS NULL) THEN
        RETURN OBJECT_CONSTRUCT(
            'STATUS',        'ERROR',
            'ERROR_MESSAGE', 'Target budget header not found or ID is NULL: ' || NVL(:TARGET_BUDGET_HEADER_ID::VARCHAR, 'NULL'),
            'SUMMARY',       OBJECT_CONSTRUCT('ImportedRows', 0, 'RejectedRows', 0)
        )::VARIANT;
    END IF;

    CREATE OR REPLACE TEMPORARY TABLE TEMP_IMPORT_STAGING (
        ROWID            INTEGER        NOT NULL AUTOINCREMENT PRIMARY KEY,
        GLACCOOUNTID     INTEGER        NULL,
        ACCOUNTNUMBER    VARCHAR(20)    NULL,
        COSTCENTERID     INTEGER        NULL,
        COSTCENTERCODE   VARCHAR(20)    NULL,
        FISCALPERIODID   INTEGER        NULL,
        FISCALYEAR       SMALLINT       NULL,
        FISCALMONTH      TINYINT        NULL,
        ORIGINALAMOUNT   NUMBER(19,4)   NULL,
        ADJUSTEDAMOUNT   NUMBER(19,4)   NULL,
        SPREADMETHODCODE VARCHAR(10)    NULL,
        NOTES            VARCHAR(500)   NULL,
        ISVALID          BOOLEAN        DEFAULT TRUE,
        VALIDATIONERRORS VARCHAR(16777216) NULL
    );

    IF (IMPORT_SOURCE = 'DIRECT') THEN
        INSERT INTO TEMP_IMPORT_STAGING (
            GLACCOOUNTID, COSTCENTERID, FISCALPERIODID,
            ORIGINALAMOUNT, ADJUSTEDAMOUNT, SPREADMETHODCODE, NOTES
        )
        SELECT
            GLACCOOUNTID, COSTCENTERID, FISCALPERIODID,
            ORIGINALAMOUNT, ADJUSTEDAMOUNT, SPREADMETHODCODE, NOTES
        FROM TEMP_IMPORT_BUDGET_DATA;

        v_total_rows := SQLROWCOUNT;

    ELSEIF (IMPORT_SOURCE = 'STAGE' AND STAGE_PATH IS NOT NULL) THEN
        v_dyn_sql :=
            'COPY INTO TEMP_IMPORT_STAGING ('
            || 'ACCOUNTNUMBER, COSTCENTERCODE, FISCALYEAR, FISCALMONTH, '
            || 'ORIGINALAMOUNT, ADJUSTEDAMOUNT, NOTES) '
            || 'FROM ' || :STAGE_PATH
            || ' FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 '
            ||                 'FIELD_OPTIONALLY_ENCLOSED_BY = ''"'')';

        EXECUTE IMMEDIATE v_dyn_sql;
        v_total_rows := SQLROWCOUNT;

    ELSE
        RETURN OBJECT_CONSTRUCT(
            'STATUS',        'ERROR',
            'ERROR_MESSAGE', 'Unsupported IMPORT_SOURCE: ' || NVL(:IMPORT_SOURCE::VARCHAR, 'NULL') || '. Use DIRECT or STAGE.',
            'SUMMARY',       OBJECT_CONSTRUCT('ImportedRows', 0, 'RejectedRows', 0)
        )::VARIANT;
    END IF;

    UPDATE TEMP_IMPORT_STAGING
    SET GLACCOOUNTID = (
        SELECT GLA.GLACCOOUNTID FROM PLANNING.GLACCOUNT GLA
        WHERE GLA.ACCOUNTNUMBER = TEMP_IMPORT_STAGING.ACCOUNTNUMBER
        LIMIT 1
    )
    WHERE GLACCOOUNTID IS NULL AND ACCOUNTNUMBER IS NOT NULL;

    UPDATE TEMP_IMPORT_STAGING
    SET COSTCENTERID = (
        SELECT CC.COSTCENTERID FROM PLANNING.COSTCENTER CC
        WHERE CC.COSTCENTERCODE = TEMP_IMPORT_STAGING.COSTCENTERCODE
        LIMIT 1
    )
    WHERE COSTCENTERID IS NULL AND COSTCENTERCODE IS NOT NULL;

    UPDATE TEMP_IMPORT_STAGING
    SET FISCALPERIODID = (
        SELECT FP.FISCALPERIODID FROM PLANNING.FISCALPERIOD FP
        WHERE FP.FISCALYEAR  = TEMP_IMPORT_STAGING.FISCALYEAR
          AND FP.FISCALMONTH = TEMP_IMPORT_STAGING.FISCALMONTH
        LIMIT 1
    )
    WHERE FISCALPERIODID IS NULL AND FISCALYEAR IS NOT NULL AND FISCALMONTH IS NOT NULL;

    IF (VALIDATION_MODE IN ('STRICT', 'LENIENT')) THEN
        UPDATE TEMP_IMPORT_STAGING
        SET ISVALID = FALSE,
            VALIDATIONERRORS = ARRAY_TO_STRING(ARRAY_COMPACT(ARRAY_CONSTRUCT(
                CASE WHEN GLACCOOUNTID   IS NULL THEN 'Invalid GL Account'   ELSE NULL END,
                CASE WHEN COSTCENTERID   IS NULL THEN 'Invalid Cost Center'  ELSE NULL END,
                CASE WHEN FISCALPERIODID IS NULL THEN 'Invalid Fiscal Period' ELSE NULL END,
                CASE WHEN ORIGINALAMOUNT IS NULL THEN 'Missing Amount'       ELSE NULL END
            )), '; ')
        WHERE GLACCOOUNTID   IS NULL
           OR COSTCENTERID   IS NULL
           OR FISCALPERIODID IS NULL
           OR ORIGINALAMOUNT IS NULL;
    END IF;

    v_invalid_rows := (SELECT COUNT(*) FROM TEMP_IMPORT_STAGING WHERE ISVALID = FALSE);
    v_valid_rows   := v_total_rows - v_invalid_rows;

    IF (VALIDATION_MODE = 'STRICT' AND v_invalid_rows > 0) THEN
        DROP TABLE IF EXISTS TEMP_IMPORT_STAGING;
        RETURN OBJECT_CONSTRUCT(
            'STATUS',        'ERROR',
            'ERROR_MESSAGE', NVL(:v_invalid_rows::VARCHAR, '0') || ' row(s) failed validation. Use LENIENT mode to skip.',
            'SUMMARY', OBJECT_CONSTRUCT(
                'TotalRows',   v_total_rows,
                'ValidRows',   v_valid_rows,
                'InvalidRows', v_invalid_rows,
                'ImportedRows', 0
            )
        )::VARIANT;
    END IF;

    BEGIN TRANSACTION;

    IF (DUPLICATE_HANDLING = 'SKIP') THEN
        INSERT INTO PLANNING.BUDGETLINEITEM (
            BUDGETHEADERID, GLACCOOUNTID, COSTCENTERID, FISCALPERIODID,
            ORIGINALAMOUNT, ADJUSTEDAMOUNT, SPREADMETHODCODE,
            SOURCESYSTEM, IMPORTBATCHID, LASTMODIFIEDDATETIME
        )
        SELECT
            :TARGET_BUDGET_HEADER_ID,
            S.GLACCOOUNTID,
            S.COSTCENTERID,
            S.FISCALPERIODID,
            S.ORIGINALAMOUNT,
            NVL(S.ADJUSTEDAMOUNT, 0),
            S.SPREADMETHODCODE,
            'BULK_IMPORT',
            :v_run_id,
            CURRENT_TIMESTAMP()
        FROM TEMP_IMPORT_STAGING S
        WHERE S.ISVALID = TRUE
          AND NOT EXISTS (
              SELECT 1 FROM PLANNING.BUDGETLINEITEM BLI
              WHERE BLI.BUDGETHEADERID = :TARGET_BUDGET_HEADER_ID
                AND BLI.GLACCOOUNTID   = S.GLACCOOUNTID
                AND BLI.COSTCENTERID   = S.COSTCENTERID
                AND BLI.FISCALPERIODID = S.FISCALPERIODID
          );

    ELSEIF (DUPLICATE_HANDLING = 'UPDATE') THEN
        MERGE INTO PLANNING.BUDGETLINEITEM AS TGT
        USING (SELECT * FROM TEMP_IMPORT_STAGING WHERE ISVALID = TRUE) AS SRC
        ON  TGT.BUDGETHEADERID = :TARGET_BUDGET_HEADER_ID
        AND TGT.GLACCOOUNTID   = SRC.GLACCOOUNTID
        AND TGT.COSTCENTERID   = SRC.COSTCENTERID
        AND TGT.FISCALPERIODID = SRC.FISCALPERIODID
        WHEN MATCHED THEN
            UPDATE SET
                TGT.ADJUSTEDAMOUNT      = SRC.ORIGINALAMOUNT - TGT.ORIGINALAMOUNT,
                TGT.LASTMODIFIEDDATETIME = CURRENT_TIMESTAMP()
        WHEN NOT MATCHED THEN
            INSERT (BUDGETHEADERID, GLACCOOUNTID, COSTCENTERID, FISCALPERIODID,
                    ORIGINALAMOUNT, ADJUSTEDAMOUNT, SPREADMETHODCODE,
                    SOURCESYSTEM, IMPORTBATCHID, LASTMODIFIEDDATETIME)
            VALUES (:TARGET_BUDGET_HEADER_ID, SRC.GLACCOOUNTID, SRC.COSTCENTERID,
                    SRC.FISCALPERIODID, SRC.ORIGINALAMOUNT, NVL(SRC.ADJUSTEDAMOUNT, 0),
                    SRC.SPREADMETHODCODE, 'BULK_IMPORT', :v_run_id, CURRENT_TIMESTAMP());

    ELSE
        INSERT INTO PLANNING.BUDGETLINEITEM (
            BUDGETHEADERID, GLACCOOUNTID, COSTCENTERID, FISCALPERIODID,
            ORIGINALAMOUNT, ADJUSTEDAMOUNT, SPREADMETHODCODE,
            SOURCESYSTEM, IMPORTBATCHID, LASTMODIFIEDDATETIME
        )
        SELECT
            :TARGET_BUDGET_HEADER_ID,
            S.GLACCOOUNTID,
            S.COSTCENTERID,
            S.FISCALPERIODID,
            S.ORIGINALAMOUNT,
            NVL(S.ADJUSTEDAMOUNT, 0),
            S.SPREADMETHODCODE,
            'BULK_IMPORT',
            :v_run_id,
            CURRENT_TIMESTAMP()
        FROM TEMP_IMPORT_STAGING S
        WHERE S.ISVALID = TRUE;
    END IF;

    v_imported_rows := SQLROWCOUNT;
    v_skipped_rows  := v_valid_rows - v_imported_rows;

    COMMIT;

    DROP TABLE IF EXISTS TEMP_IMPORT_STAGING;

    RETURN OBJECT_CONSTRUCT(
        'STATUS',  'COMPLETED',
        'SUMMARY', OBJECT_CONSTRUCT(
            'ImportSource',    IMPORT_SOURCE,
            'TotalRows',       v_total_rows,
            'ValidRows',       v_valid_rows,
            'InvalidRows',     v_invalid_rows,
            'ImportedRows',    v_imported_rows,
            'SkippedRows',     v_skipped_rows,
            'DuplicatePolicy', DUPLICATE_HANDLING
        ),
        'RUN_ID',  v_run_id
    )::VARIANT;

EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        DROP TABLE IF EXISTS TEMP_IMPORT_STAGING;
        RETURN OBJECT_CONSTRUCT(
            'STATUS',        'ERROR',
            'ERROR_MESSAGE', SQLERRM,
            'SUMMARY',       OBJECT_CONSTRUCT('ImportedRows', 0, 'RejectedRows', 0)
        )::VARIANT;
END;
$$;
