USE DATABASE PLANNING_DB;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA PLANNING;

SHOW TABLES   IN SCHEMA PLANNING;
SHOW FUNCTIONS IN SCHEMA PLANNING;
SHOW PROCEDURES IN SCHEMA PLANNING;

INSERT INTO PLANNING.FISCALPERIOD (
    FISCALYEAR, FISCALQUARTER, FISCALMONTH, PERIODNAME,
    PERIODSTARTDATE, PERIODENDDATE, ISCLOSED
) VALUES (2024, 1, 1, 'Jan 2024', '2024-01-01', '2024-01-31', FALSE);

SELECT * FROM PLANNING.FISCALPERIOD;

INSERT INTO PLANNING.COSTCENTER (
    COSTCENTERCODE, COSTCENTERNAME, PARENTCOSTCENTERID, HIERARCHYPATH,
    HIERARCHYLEVEL, ISACTIVE, EFFECTIVEFROMDATE, ALLOCATIONWEIGHT
) VALUES ('CORP', 'Corporate', NULL, '/1/', 0, TRUE, '2024-01-01', 1.0);

INSERT INTO PLANNING.COSTCENTER (
    COSTCENTERCODE, COSTCENTERNAME, PARENTCOSTCENTERID, HIERARCHYPATH,
    HIERARCHYLEVEL, ISACTIVE, EFFECTIVEFROMDATE, ALLOCATIONWEIGHT
)
SELECT 'FIN', 'Finance', COSTCENTERID, '/1/2/', 1, TRUE, '2024-01-01', 0.4
FROM PLANNING.COSTCENTER WHERE COSTCENTERCODE = 'CORP';

SELECT * FROM PLANNING.COSTCENTER ORDER BY HIERARCHYLEVEL;

INSERT INTO PLANNING.GLACCOUNT (
    ACCOUNTNUMBER, ACCOUNTNAME, ACCOUNTTYPE, NORMALBALANCE,
    ISPOSTABLE, ISBUDGETABLE, INTERCOMPANYFLAG
) VALUES ('5000', 'Salaries', 'X', 'D', TRUE, TRUE, FALSE);

INSERT INTO PLANNING.GLACCOUNT (
    ACCOUNTNUMBER, ACCOUNTNAME, ACCOUNTTYPE, NORMALBALANCE,
    ISPOSTABLE, ISBUDGETABLE, INTERCOMPANYFLAG
) VALUES ('4000', 'IC Revenue', 'R', 'C', TRUE, TRUE, TRUE);

SELECT * FROM PLANNING.GLACCOUNT ORDER BY ACCOUNTNUMBER;

INSERT INTO PLANNING.BUDGETHEADER (
    BUDGETCODE, BUDGETNAME, BUDGETTYPE, SCENARIOTYPE, FISCALYEAR,
    STARTPERIODID, ENDPERIODID, STATUSCODE
)
SELECT
    'BUD-2024-BASE', 'FY2024 Base Budget', 'ANNUAL', 'BASE', 2024,
    FP.FISCALPERIODID, FP.FISCALPERIODID, 'APPROVED'
FROM PLANNING.FISCALPERIOD FP
WHERE FP.FISCALYEAR = 2024 AND FP.FISCALMONTH = 1;

SELECT * FROM PLANNING.BUDGETHEADER ORDER BY BUDGETHEADERID;

INSERT INTO PLANNING.BUDGETLINEITEM (
    BUDGETHEADERID, GLACCOOUNTID, COSTCENTERID, FISCALPERIODID,
    ORIGINALAMOUNT, ADJUSTEDAMOUNT, FINALAMOUNT
)
SELECT
    BH.BUDGETHEADERID,
    GLA.GLACCOOUNTID,
    CC.COSTCENTERID,
    FP.FISCALPERIODID,
    120000.00, 0.00, 120000.00
FROM PLANNING.BUDGETHEADER BH
CROSS JOIN PLANNING.GLACCOUNT GLA
CROSS JOIN PLANNING.COSTCENTER CC
CROSS JOIN PLANNING.FISCALPERIOD FP
WHERE BH.BUDGETCODE  = 'BUD-2024-BASE'
  AND GLA.ACCOUNTNUMBER = '5000'
  AND CC.COSTCENTERCODE = 'FIN'
  AND FP.FISCALYEAR = 2024 AND FP.FISCALMONTH = 1;

INSERT INTO PLANNING.BUDGETLINEITEM (
    BUDGETHEADERID, GLACCOOUNTID, COSTCENTERID, FISCALPERIODID,
    ORIGINALAMOUNT, ADJUSTEDAMOUNT, FINALAMOUNT
)
SELECT
    BH.BUDGETHEADERID,
    GLA.GLACCOOUNTID,
    CC.COSTCENTERID,
    FP.FISCALPERIODID,
    50000.00, 0.00, 50000.00
FROM PLANNING.BUDGETHEADER BH
CROSS JOIN PLANNING.GLACCOUNT GLA
CROSS JOIN PLANNING.COSTCENTER CC
CROSS JOIN PLANNING.FISCALPERIOD FP
WHERE BH.BUDGETCODE  = 'BUD-2024-BASE'
  AND GLA.ACCOUNTNUMBER = '4000'
  AND CC.COSTCENTERCODE = 'CORP'
  AND FP.FISCALYEAR = 2024 AND FP.FISCALMONTH = 1;

SELECT COUNT(*) AS LINE_ITEM_COUNT FROM PLANNING.BUDGETLINEITEM;

INSERT INTO PLANNING.ALLOCATIONRULE (
    RULECODE, RULENAME, RULETYPE, ALLOCATIONMETHOD,
    SOURCECOSTCENTERID, TARGETSPECIFICATION, ALLOCATIONBASIS,
    ALLOCATIONPERCENTAGE, EXECUTIONSEQUENCE, EFFECTIVEFROMDATE, ISACTIVE
)
SELECT
    'AR-FIN-CORP',
    'Finance → Corporate 40% Allocation',
    'DIRECT',
    'FIXED_PCT',
    CC.COSTCENTERID,
    PARSE_JSON('{
        "AllocationTargets": [
            {
              "CostCenterID": ' || CORP.COSTCENTERID::VARCHAR || ',
              "CostCenterCode": "CORP",
              "AllocationPercentage": 0.40,
              "Priority": 1
            }
        ]
    }'),
    'EQUAL',
    0.4000,
    100,
    '2024-01-01',
    TRUE
FROM PLANNING.COSTCENTER CC
CROSS JOIN PLANNING.COSTCENTER CORP
WHERE CC.COSTCENTERCODE = 'FIN'
  AND CORP.COSTCENTERCODE = 'CORP';

SELECT * FROM PLANNING.ALLOCATIONRULE;

SELECT PLANNING.FN_GETHIERARCHYPATH(
    (SELECT MAX(COSTCENTERID) FROM PLANNING.COSTCENTER WHERE COSTCENTERCODE = 'FIN'),
    ' > '
) AS HIERARCHY_PATH;

SELECT PLANNING.FN_GETALLOCATIONFACTOR(
    (SELECT MAX(COSTCENTERID) FROM PLANNING.COSTCENTER WHERE COSTCENTERCODE = 'CORP'),
    (SELECT MAX(COSTCENTERID) FROM PLANNING.COSTCENTER WHERE COSTCENTERCODE = 'FIN'),
    'EQUAL',
    (SELECT MAX(FISCALPERIODID) FROM PLANNING.FISCALPERIOD WHERE FISCALYEAR=2024 AND FISCALMONTH=1),
    NULL
) AS ALLOCATION_FACTOR;

SELECT * FROM TABLE(PLANNING.TVF_GETBUDGETVARIANCE(
    (SELECT MAX(BUDGETHEADERID) FROM PLANNING.BUDGETHEADER WHERE BUDGETCODE = 'BUD-2024-BASE'),
    (SELECT MAX(BUDGETHEADERID) FROM PLANNING.BUDGETHEADER WHERE BUDGETCODE = 'BUD-2024-BASE')
)) ORDER BY ACCOUNTNUMBER;

SELECT * FROM TABLE(PLANNING.TVF_EXPLODECOSTCENTERHIERARCHY(NULL::INTEGER, 10, FALSE, NULL::DATE))
ORDER BY HIERARCHYLEVEL, COSTCENTERCODE;

SELECT * FROM PLANNING.VW_BUDGETCONSOLIDATIONSUMMARY
ORDER BY BUDGETCODE, ACCOUNTNUMBER;

SELECT * FROM PLANNING.VW_ALLOCATIONRULETARGETS;

CALL PLANNING.USP_PROCESSBUDGETCONSOLIDATION(
    SOURCE_BUDGET_HEADER_ID   => (SELECT MAX(BUDGETHEADERID) FROM PLANNING.BUDGETHEADER WHERE BUDGETCODE = 'BUD-2024-BASE'),
    CONSOLIDATION_TYPE        => 'FULL',
    INCLUDE_ELIMINATIONS      => TRUE,
    RECALCULATE_ALLOCATIONS   => TRUE,
    USER_ID                   => 1,
    DEBUG_MODE                => TRUE
);

SELECT BUDGETHEADERID, BUDGETCODE, BUDGETTYPE, STATUSCODE
FROM PLANNING.BUDGETHEADER
WHERE BUDGETTYPE = 'CONSOLIDATED'
ORDER BY CREATEDDATETIME DESC LIMIT 5;

SELECT COUNT(*) AS CONSOLIDATED_LINE_ITEMS
FROM PLANNING.BUDGETLINEITEM BLI
INNER JOIN PLANNING.BUDGETHEADER BH ON BLI.BUDGETHEADERID = BH.BUDGETHEADERID
WHERE BH.BUDGETTYPE = 'CONSOLIDATED';

CALL PLANNING.USP_EXECUTECOSTALLOCATION(
    BUDGET_HEADER_ID    => (SELECT MAX(BUDGETHEADERID) FROM PLANNING.BUDGETHEADER WHERE BUDGETCODE = 'BUD-2024-BASE'),
    ALLOCATION_RULE_IDS => NULL,
    P_FISCAL_PERIOD_ID  => NULL,
    DRY_RUN             => TRUE,
    MAX_ITERATIONS      => 10
);

CALL PLANNING.USP_EXECUTECOSTALLOCATION(
    BUDGET_HEADER_ID    => (SELECT MAX(BUDGETHEADERID) FROM PLANNING.BUDGETHEADER WHERE BUDGETCODE = 'BUD-2024-BASE'),
    DRY_RUN             => FALSE,
    MAX_ITERATIONS      => 10
);

SELECT COUNT(*) AS ALLOCATED_COUNT
FROM PLANNING.BUDGETLINEITEM
WHERE ISALLOCATED = TRUE
  AND BUDGETHEADERID = (SELECT MAX(BUDGETHEADERID) FROM PLANNING.BUDGETHEADER WHERE BUDGETCODE = 'BUD-2024-BASE');

CALL PLANNING.USP_GENERATEROLLINGFORECAST(
    BASE_BUDGET_HEADER_ID => (SELECT MAX(BUDGETHEADERID) FROM PLANNING.BUDGETHEADER WHERE BUDGETCODE = 'BUD-2024-BASE'),
    HISTORICAL_PERIODS    => 1,
    FORECAST_PERIODS      => 3,
    FORECAST_METHOD       => 'WEIGHTED_AVERAGE',
    OUTPUT_FORMAT         => 'SUMMARY'
);

SELECT BUDGETCODE, BUDGETTYPE, STATUSCODE
FROM PLANNING.BUDGETHEADER
WHERE BUDGETTYPE = 'ROLLING'
ORDER BY CREATEDDATETIME DESC LIMIT 3;

CALL PLANNING.USP_RECONCILEINTERCOMPANYBALANCES(
    BUDGET_HEADER_ID        => (SELECT MAX(BUDGETHEADERID) FROM PLANNING.BUDGETHEADER WHERE BUDGETCODE = 'BUD-2024-BASE'),
    TOLERANCE_AMOUNT        => 0.01,
    AUTO_CREATE_ADJUSTMENTS => FALSE
);

CALL PLANNING.USP_PERFORMFINANCIALCLOSE(
    CLOSE_PERIOD_ID            => (SELECT MAX(FISCALPERIODID) FROM PLANNING.FISCALPERIOD WHERE FISCALYEAR=2024 AND FISCALMONTH=1),
    CLOSE_SCENARIO_TYPE        => 'BASE',
    INCLUDE_CONSOLIDATION      => TRUE,
    INCLUDE_COST_ALLOCATION    => TRUE,
    INCLUDE_IC_RECONCILIATION  => TRUE,
    GENERATE_ROLLING_FORECAST  => FALSE,
    VALIDATE_BEFORE_CLOSE      => TRUE,
    DEBUG_MODE                 => FALSE
);

SELECT FISCALPERIODID, PERIODNAME, ISCLOSED, CLOSEDDATETIME
FROM PLANNING.FISCALPERIOD
WHERE FISCALYEAR = 2024 AND FISCALMONTH = 1;

SELECT * FROM PLANNING.NOTIFICATION_LOG LIMIT 5;

CREATE TEMPORARY TABLE IF NOT EXISTS TEMP_IMPORT_BUDGET_DATA (
    GLACCOOUNTID     INTEGER,
    COSTCENTERID     INTEGER,
    FISCALPERIODID   INTEGER,
    ORIGINALAMOUNT   NUMBER(19,4),
    ADJUSTEDAMOUNT   NUMBER(19,4),
    SPREADMETHODCODE VARCHAR(10),
    NOTES            VARCHAR(500)
);

INSERT INTO TEMP_IMPORT_BUDGET_DATA
SELECT
    GLA.GLACCOOUNTID,
    CC.COSTCENTERID,
    FP.FISCALPERIODID,
    75000.00,
    0.00,
    NULL,
    'Test direct import'
FROM PLANNING.GLACCOUNT GLA
CROSS JOIN PLANNING.COSTCENTER CC
CROSS JOIN PLANNING.FISCALPERIOD FP
WHERE GLA.ACCOUNTNUMBER  = '5000'
  AND CC.COSTCENTERCODE  = 'CORP'
  AND FP.FISCALYEAR = 2024 AND FP.FISCALMONTH = 1;

INSERT INTO PLANNING.BUDGETHEADER (
    BUDGETCODE, BUDGETNAME, BUDGETTYPE, SCENARIOTYPE, FISCALYEAR,
    STARTPERIODID, ENDPERIODID, STATUSCODE
)
SELECT 'BUD-2024-IMPORT', 'FY2024 Import Test', 'ANNUAL', 'BASE', 2024,
       FISCALPERIODID, FISCALPERIODID, 'APPROVED'
FROM PLANNING.FISCALPERIOD WHERE FISCALYEAR=2024 AND FISCALMONTH=1;

CALL PLANNING.USP_BULKIMPORTBUDGETDATA(
    IMPORT_SOURCE           => 'DIRECT',
    TARGET_BUDGET_HEADER_ID => (SELECT MAX(BUDGETHEADERID) FROM PLANNING.BUDGETHEADER WHERE BUDGETCODE='BUD-2024-IMPORT'),
    STAGE_PATH              => NULL,
    STAGING_TABLE_NAME      => NULL,
    VALIDATION_MODE         => 'LENIENT',
    DUPLICATE_HANDLING      => 'SKIP',
    BATCH_SIZE              => 1000
);

SELECT BLI.BUDGETLINEITEMID, GLA.ACCOUNTNUMBER, CC.COSTCENTERCODE, BLI.ORIGINALAMOUNT
FROM PLANNING.BUDGETLINEITEM BLI
INNER JOIN PLANNING.BUDGETHEADER  BH  ON BLI.BUDGETHEADERID = BH.BUDGETHEADERID
INNER JOIN PLANNING.GLACCOUNT     GLA ON BLI.GLACCOOUNTID   = GLA.GLACCOOUNTID
INNER JOIN PLANNING.COSTCENTER    CC  ON BLI.COSTCENTERID   = CC.COSTCENTERID
WHERE BH.BUDGETCODE = 'BUD-2024-IMPORT';

SELECT
    'FISCALPERIOD'      AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM PLANNING.FISCALPERIOD     UNION ALL
SELECT 'COSTCENTER',             COUNT(*) FROM PLANNING.COSTCENTER                          UNION ALL
SELECT 'GLACCOUNT',              COUNT(*) FROM PLANNING.GLACCOUNT                           UNION ALL
SELECT 'ALLOCATIONRULE',         COUNT(*) FROM PLANNING.ALLOCATIONRULE                      UNION ALL
SELECT 'BUDGETHEADER',           COUNT(*) FROM PLANNING.BUDGETHEADER                        UNION ALL
SELECT 'BUDGETLINEITEM',         COUNT(*) FROM PLANNING.BUDGETLINEITEM                      UNION ALL
SELECT 'CONSOLIDATIONJOURNAL',   COUNT(*) FROM PLANNING.CONSOLIDATIONJOURNAL                UNION ALL
SELECT 'NOTIFICATION_LOG',       COUNT(*) FROM PLANNING.NOTIFICATION_LOG
ORDER BY TABLE_NAME;
