USE DATABASE PLANNING_DB;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA PLANNING;

CREATE OR REPLACE VIEW PLANNING.VW_BUDGETCONSOLIDATIONSUMMARY AS
SELECT
    BH.BUDGETHEADERID,
    BH.BUDGETCODE,
    BH.BUDGETNAME,
    BH.BUDGETTYPE,
    BH.SCENARIOTYPE,
    BH.FISCALYEAR,
    FP.FISCALPERIODID,
    FP.FISCALQUARTER,
    FP.FISCALMONTH,
    FP.PERIODNAME,
    GLA.GLACCOOUNTID,
    GLA.ACCOUNTNUMBER,
    GLA.ACCOUNTNAME,
    GLA.ACCOUNTTYPE,
    CC.COSTCENTERID,
    CC.COSTCENTERCODE,
    CC.COSTCENTERNAME,
    CC.PARENTCOSTCENTERID,
    SUM(BLI.ORIGINALAMOUNT)                          AS TOTALORIGINALAMOUNT,
    SUM(BLI.ADJUSTEDAMOUNT)                          AS TOTALADJUSTEDAMOUNT,
    SUM(BLI.ORIGINALAMOUNT + BLI.ADJUSTEDAMOUNT)     AS TOTALFINALAMOUNT,
    SUM(NVL(BLI.LOCALCURRENCYAMOUNT, 0))             AS TOTALLOCALCURRENCY,
    SUM(NVL(BLI.REPORTINGCURRENCYAMOUNT, 0))         AS TOTALREPORTINGCURRENCY,
    COUNT(*)                                          AS LINEITEMCOUNT
FROM PLANNING.BUDGETLINEITEM BLI
INNER JOIN PLANNING.BUDGETHEADER  BH  ON BLI.BUDGETHEADERID  = BH.BUDGETHEADERID
INNER JOIN PLANNING.GLACCOUNT     GLA ON BLI.GLACCOOUNTID    = GLA.GLACCOOUNTID
INNER JOIN PLANNING.COSTCENTER    CC  ON BLI.COSTCENTERID    = CC.COSTCENTERID
INNER JOIN PLANNING.FISCALPERIOD  FP  ON BLI.FISCALPERIODID  = FP.FISCALPERIODID
GROUP BY
    BH.BUDGETHEADERID, BH.BUDGETCODE, BH.BUDGETNAME, BH.BUDGETTYPE,
    BH.SCENARIOTYPE, BH.FISCALYEAR,
    FP.FISCALPERIODID, FP.FISCALQUARTER, FP.FISCALMONTH, FP.PERIODNAME,
    GLA.GLACCOOUNTID, GLA.ACCOUNTNUMBER, GLA.ACCOUNTNAME, GLA.ACCOUNTTYPE,
    CC.COSTCENTERID, CC.COSTCENTERCODE, CC.COSTCENTERNAME, CC.PARENTCOSTCENTERID;

CREATE OR REPLACE VIEW PLANNING.VW_ALLOCATIONRULETARGETS AS
WITH FLATTENED AS (
    SELECT
        AR.ALLOCATIONRULEID,
        AR.RULECODE,
        AR.RULENAME,
        AR.RULETYPE,
        AR.ALLOCATIONMETHOD,
        AR.EXECUTIONSEQUENCE,
        AR.EFFECTIVEFROMDATE,
        AR.EFFECTIVETODATE,
        AR.ISACTIVE                               AS RULEISACTIVE,
        T.VALUE:CostCenterID::INTEGER             AS TARGETCOSTCENTERID,
        T.VALUE:CostCenterCode::VARCHAR           AS TARGETCOSTCENTERCODE,
        T.VALUE:AllocationPercentage::NUMBER(8,6) AS TARGETALLOCATIONPCT,
        T.VALUE:Priority::INTEGER                 AS TARGETPRIORITY,
        T.VALUE:AccountFilter::VARCHAR            AS ACCOUNTFILTER,
        T.VALUE:ExcludePattern::VARCHAR           AS EXCLUDEPATTERN,
        (T.VALUE:Conditions IS NOT NULL
            AND ARRAY_SIZE(T.VALUE:Conditions) > 0) AS HASCONDITIONS,
        T.VALUE:Conditions                        AS CONDITIONSVARIANT
    FROM PLANNING.ALLOCATIONRULE AR,
         LATERAL FLATTEN(INPUT => AR.TARGETSPECIFICATION:AllocationTargets) T
)
SELECT
    F.ALLOCATIONRULEID,
    F.RULECODE,
    F.RULENAME,
    F.RULETYPE,
    F.ALLOCATIONMETHOD,
    F.EXECUTIONSEQUENCE,
    F.TARGETCOSTCENTERID,
    F.TARGETCOSTCENTERCODE,
    F.TARGETALLOCATIONPCT,
    F.TARGETPRIORITY,
    F.ACCOUNTFILTER,
    F.EXCLUDEPATTERN,
    F.HASCONDITIONS,
    F.CONDITIONSVARIANT,
    CC.COSTCENTERNAME                             AS TARGETCOSTCENTERNAME,
    CC.PARENTCOSTCENTERID                         AS TARGETPARENTCOSTCENTERID,
    CC.ISACTIVE                                   AS TARGETISACTIVE,
    F.EFFECTIVEFROMDATE,
    F.EFFECTIVETODATE,
    F.RULEISACTIVE
FROM FLATTENED F
LEFT JOIN PLANNING.COSTCENTER CC
    ON  CC.COSTCENTERID   = F.TARGETCOSTCENTERID
    OR  CC.COSTCENTERCODE = F.TARGETCOSTCENTERCODE;
